### ISSUE TITLE
Crud and Join operations?

### ISSUE THREAD

**Issue by twoxfh** [memorylorry/JSON2SQL#1]
Any plans to support crud and joins? Crud operations would be useful and could reuse whereFilter for update and deletes. Bulk loading would be useful too with limits. The work around for joins is a view, but could be very handy.   

Thoughts?

**Comment by memorylorry** [comment]
Thanks for your advise. But you could make join operation with **table attribute**. I regrad a select sql into a slice. You can have a look [**Class Slice**](https://github.com/memorylorry/JSON2SQL/blob/master/src/main/java/com/github/memorylorry/type/Slice.java).

**Comment by memorylorry** [comment]
If you also get interested in this project. We could improve it day by day.

**Comment by twoxfh** [comment]
How about generating schemas from SQL database to validate submitting Json document? Preventing SQL injection would be key as well.

**Comment by memorylorry** [comment]
That sounds great. But my main point is to composite a SQL by using page parameters firstly. If it is enough time in future or it has high-value to do, I will think it as more important. 
And thinking a stage. I need to make data visualization easily. Every my page commonly has several charts(like line,pie,bar etc.). Every one of these charts is represented by one JSON Object, which is regraded as a slice. So a JSON is transformed to a SQL can helps get data from datasource.
